language: node_js
node_js:
  - "node"
  - "lts/carbon"
  - "lts/dubnium"
script:
  - yarn lint
  - yarn test:unit
after_script:
  - cat ./coverage/lcov.info | coveralls
before_deploy:
  - yarn build
  - cp CNAME dist/
deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
